export const CATEGORY_RULES = [
  { category: 'Programming', hostnames: ['github.com', 'gitlab.com', 'bitbucket.org', 'replit.com', 'codesandbox.io', 'codepen.io', 'stackoverflow.com', 'dev.to'] },
  { category: 'Documentation', hostnames: ['developer.mozilla.org', 'react.dev', 'nodejs.org', 'expressjs.com', 'docs.python.org', 'docs.oracle.com', 'spring.io', 'angular.dev', 'vuejs.org', 'tailwindcss.com', 'nextjs.org', 'vitejs.dev', 'docs.docker.com', 'kubernetes.io', 'postgresql.org', 'mongodb.com', 'docs.mongodb.com', 'mdn.dev'] },
  { category: 'Learning', hostnames: ['geeksforgeeks.org', 'freecodecamp.org', 'coursera.org', 'udemy.com', 'edx.org', 'codecademy.com', 'tutorialspoint.com', 'w3schools.com', 'leetcode.com', 'hackerrank.com'] },
  { category: 'AI', hostnames: ['chat.openai.com', 'chatgpt.com', 'claude.ai', 'gemini.google.com', 'perplexity.ai', 'openai.com'] },
  { category: 'Cloud', hostnames: ['aws.amazon.com', 'azure.microsoft.com', 'cloud.google.com', 'digitalocean.com', 'linode.com'] },
  { category: 'DevOps', hostnames: ['docker.com', 'docs.docker.com', 'terraform.io', 'jenkins.io', 'github.com/actions', 'kubernetes.io'] },
  { category: 'Career', hostnames: ['linkedin.com', 'indeed.com', 'glassdoor.com', 'angel.co', 'wellfound.com'] },
  { category: 'Finance', hostnames: ['investopedia.com', 'finance.yahoo.com', 'bloomberg.com', 'coinmarketcap.com', 'coinbase.com'] },
  { category: 'News', hostnames: ['news.ycombinator.com', 'bbc.com', 'reuters.com', 'cnn.com', 'nytimes.com', 'theguardian.com'] },
  { category: 'Shopping', hostnames: ['amazon.com', 'amazon.in', 'amazon.co.uk', 'flipkart.com', 'myntra.com', 'meesho.com', 'ajio.com', 'nykaa.com', 'blinkit.com', 'swiggy.com', 'zomato.com', 'zepto.com', 'bigbasket.com', 'walmart.com', 'target.com', 'ebay.com', 'etsy.com', 'aliexpress.com', 'shopify.com'] },
  { category: 'Entertainment', hostnames: ['netflix.com', 'hulu.com', 'primevideo.com', 'disneyplus.com', 'twitch.tv', 'max.com', 'hbomax.com', 'peacocktv.com', 'tv.apple.com', 'paramountplus.com', 'hotstar.com', 'sonyliv.com', 'zee5.com', 'jiocinema.com'] },
  { category: 'Music', hostnames: ['spotify.com', 'soundcloud.com', 'bandcamp.com', 'apple.com'] },
  { category: 'Sports', hostnames: ['espn.com', 'nba.com', 'cricbuzz.com', 'sports.yahoo.com', 'football.com'] },
  { category: 'Gaming', hostnames: ['steamcommunity.com', 'steam.com', 'riotgames.com', 'epicgames.com', 'minecraft.net'] },
  { category: 'Movies', hostnames: ['imdb.com', 'letterboxd.com', 'rottentomatoes.com'] },
  { category: 'Travel', hostnames: ['expedia.com', 'booking.com', 'airbnb.com', 'tripadvisor.com', 'skyscanner.com'] },
  { category: 'Social', hostnames: ['instagram.com', 'facebook.com', 'twitter.com', 'x.com', 'reddit.com', 'pinterest.com', 'tumblr.com'] },
  { category: 'Productivity', hostnames: ['notion.so', 'trello.com', 'asana.com', 'jira.atlassian.com', 'clickup.com', 'monday.com', 'docs.google.com', 'drive.google.com', 'sheets.google.com', 'slides.google.com', 'keep.google.com', 'calendar.google.com', 'evernote.com'] },
  { category: 'Search', hostnames: ['google.com', 'bing.com', 'duckduckgo.com', 'search.yahoo.com', 'baidu.com', 'yandex.com'] },
  { category: 'Email', hostnames: ['mail.google.com', 'outlook.office.com', 'proton.me', 'mail.yahoo.com', 'outlook.live.com'] },
  { category: 'Communication', hostnames: ['discord.com', 'slack.com', 'teams.microsoft.com', 'meet.google.com', 'zoom.us', 'webex.com'] },
  { category: 'Design', hostnames: ['figma.com', 'dribbble.com', 'behance.net', 'canva.com'] },
  { category: 'Business', hostnames: ['forbes.com', 'businessinsider.com'] },
  { category: 'Health', hostnames: ['webmd.com', 'mayoclinic.org', 'healthline.com', 'medicalnewstoday.com'] },
];

export const CATEGORY_MAP = Object.fromEntries(CATEGORY_RULES.map((rule) => [rule.category, rule.category]));

export const CATEGORY_WEIGHTS = {
  Programming: 5,
  Learning: 4,
  Documentation: 4,
  AI: 4,
  Cloud: 4,
  DevOps: 4,
  Career: 3,
  Finance: 3,
  News: 1,
  Entertainment: -2,
  Music: -1,
  Shopping: -1,
  Social: -3,
  Productivity: 3,
  Communication: 2,
  Search: 0,
  Email: 1,
  Design: 2,
  Business: 2,
  Health: 1,
  Gaming: -1,
  Movies: -2,
  Travel: -1,
  Other: 0,
};

export const CATEGORY_COLORS = {
  Programming: '#2563eb',
  AI: '#8b5cf6',
  Career: '#14b8a6',
  Learning: '#f59e0b',
  Documentation: '#06b6d4',
  Cloud: '#0ea5e9',
  DevOps: '#22c55e',
  Shopping: '#ef4444',
  Social: '#f97316',
  Entertainment: '#ec4899',
  Music: '#6366f1',
  Productivity: '#10b981',
  Communication: '#3b82f6',
  Search: '#64748b',
  Email: '#475569',
  Design: '#f43f5e',
  Business: '#84cc16',
  Health: '#14b8a6',
  Gaming: '#a855f7',
  Movies: '#f59e0b',
  Travel: '#9FA1FF',
  Sports: '#fb923c',
  Finance: '#eab308',
  News: '#94a3b8',
  Other: '#64748b',
};
